name: musicoo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.1
  go_router: ^5.2.4
  mobx: ^2.0.7+7
  flutter_mobx: ^2.0.6+3
  debounce_throttle: ^2.0.0
  freezed: ^2.3.2
  splashscreen: ^1.3.5
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  avatar_glow: ^2.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  pinput: ^2.2.20
  cached_network_image: ^3.2.3
  flutter_branch_sdk: ^6.4.0
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+2
flutter:
  uses-material-design: true
  assets:
    - assets/
